import Header from "../components/anotherHeaderAndFooter/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Header />
            <body className="margin">{children}</body>
        </html>
    );
}
